---
- name: setup compose dir structure
  file:
    path: "{{ compose_project_dir }}/{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    recurse: yes
    mode: 0755
  with_items:
  - wordpress
  - wp-db-data
  - nginx
  - logs/nginx
  tags:
    - dir_ops

- name: create docker-compose.yml file
  file:
    path: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: touch
  tags:
    - file_ops

- name: deploy docker compose project for (Wordpress/MariaDB/Nginx containers)
  template:
    src: docker-compose.j2
    dest: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - deploy_compose

- name: deploy wordpress nginx virtual host
  template:
    src: wordpress-nginx.j2
    dest: "{{ compose_project_dir }}/nginx/wordpress.conf"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - gen_nginx

- name: copy index.html
  template:
    src: wordpress-index.html
    dest: "{{ compose_project_dir }}/wordpress/index.html"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - index

- name: run docker-compose up
  command: docker-compose up -d
  args:
    chdir: "{{ compose_project_dir }}"
  tags:
    - compose_run

- name: giving some time for project (all 3 containers) to start-up
  pause:
    seconds: 10
